Introduce poetry
N3PDF/yadism pull request #116
Opened 2021-07-15 17:54 UTC by AleCandido

Add:

- [ ] poetry
- [ ] poetry dynamic versioning
- [ ] poetry task runner

2021-07-23 13:21 UTC, AleCandido commented
I also removed old and unused stuffs, and the only two pain points left behind are:
- non-pip dependencies (that have to be installed manually into the poetry environment)
  - and therefore the problem of running benchmarks in CI
- incomplete coverage (i.e. unit tests) that was not the goal of this PR

2021-08-16 08:22 UTC, felixhekhorn requested changes

2021-08-16 08:22 UTC, felixhekhorn commented on benchmarks/pyproject.toml
> +authors = ["Alessandro Candido <candido.ale@gmail.com>"]
Maybe you want to list the three of us? ;-)

2021-08-16 08:22 UTC, felixhekhorn commented on src/yadism/__init__.py
> +__version__ = "0.0.0"
this is also used inside the docs, isn't it?

2021-08-16 09:36 UTC, felixhekhorn approved these changes

2021-08-16 09:38 UTC, merged